version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_PASSWORD: bajwali123%^&*
      DB_USER: dev
      DB_NAME: evershop
    networks:
      - myevershop
    depends_on:
      - database
    ports:
      - 3000:3000
  
  # The PostgreSQL database:
  database:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: bajwali123%^&*
      POSTGRES_USER: dev
      POSTGRES_DB: evershop
    ports:
      - "5434:5432"
    networks:
      - myevershop

networks:
  myevershop:
    name: MyEverShop
    driver: bridge

volumes:
  postgres-data:

